### ISSUE TITLE
.section_container mixes up with bg

### ISSUE THREAD

**Issue by JatSh1804** [deoliaman00/Portfolio2022.github.io#1]
use some box-shadow for .section_container 

```css
.section_container{    
   box-shadow: rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px  12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px;    
}
```
